name: fastembedr-benchmark-r
channels:
  - conda-forge
dependencies:
  - r-base>=4.4
  - r-remotes
  - r-rcpp
  - r-jsonlite
  - r-knitr
  - r-rmarkdown
  - r-testthat
  - r-rtsne
  - r-uwot
  - r-umap
  - r-igraph
  - r-float
  - compilers
  - make
  - cmake
  - pkg-config
  - fftw
  - git
  - python
